### ISSUE TITLE
First Install fails to find workspace folders and hangs

### ISSUE THREAD

**Issue by borpin** [design4pro/vscode-workspace-manager#39]
Firstly, this is exactly what I want!

**Describe the bug**
On first install, the extension looks for workspace folders.

Eventually the VSCode window hangs and needs to be re-opened.

**To Reproduce**
1. Install
2. open the Explorer panel

**Expected behavior**

It doesn't hang.

Suggest auto find is disabled by default and option to select folders is created (could not see one).

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser N/A
 - Version latest!

**Smartphone (please complete the following information):**

**Additional context**

**Comment by tellkonkle** [comment]
Same issue here.

**Comment by Masterkraft0r** [comment]
same issue with me. is there any progress?

**Comment by Mundayne** [comment]
Same here! Update would be good.
